# Generated by Django 5.0.6 on 2026-05-24 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel & Procurement'), ('UTILITY', 'Utility Electricity'), ('CONCUR', 'Corporate Travel (Concur)')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 – Direct Emissions'), ('SCOPE_2', 'Scope 2 – Purchased Energy'), ('SCOPE_3', 'Scope 3 – Value Chain')], max_length=10)),
                ('category', models.CharField(max_length=200)),
                ('activity_description', models.CharField(max_length=500)),
                ('activity_quantity', models.DecimalField(decimal_places=4, max_digits=16)),
                ('activity_unit', models.CharField(max_length=30)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit_normalized', models.CharField(max_length=20)),
                ('emission_factor_used', models.CharField(blank=True, max_length=200)),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=2)),
                ('raw_row', models.JSONField()),
                ('source_row_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged – Needs Attention'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('needs_review_reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.ingestionrun')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='records_emi_tenant__8039e2_idx'), models.Index(fields=['tenant', 'scope'], name='records_emi_tenant__058101_idx'), models.Index(fields=['tenant', 'period_start', 'period_end'], name='records_emi_tenant__cda3ff_idx'), models.Index(fields=['source_type', 'source_row_id'], name='records_emi_source__bde52d_idx')],
            },
        ),
    ]
